### ISSUE TITLE
Investigate a new way for L0Hadron TOS emulation

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/TrackerOnlyEmu#5]
We may need a new way to emulated L0Hadron TOS. Let's use this issue to track our progress on investigations to a potential new way, while keeping the #3 as-is for now in case we can fully reuse RD+'s emulation.

## Getting started with this project
@manuelfs has offered to help on this investigation. I need to provide some documentation to get him started

### Bare minimum: run this project

Follow the top instructions of the README. I think this project can run outside of nix. Also, this time the `Makefile` really is just a shell script so it should be easy to understand what's going for each target

You can also read the _Develop this project_ for more info.

### Re-generate L0Hadron TOS plots

This is done in `lhcb-ntuples-gen`. Open the `studies/trigger_emulation-l0_hadron_tos_debug` folder and run the script inside that folder.

### ntuple generations

Note: `samples` is a folder in this project; `studies` a folder in `lhcb-ntuples-gen`.

- The `samples/rdx-tracker_only.root` is generated in `studies/ntuple-RDX_trigger_emulation_sample`. This is used for testing **APPLICATION** of trigger emulation
- The `samples/rdx-bdt_train_sample.root` is generated in `studies/ntuple-RDX_l0_hadron_tos_training_sample`. This is used as the input to L0Hadron TOS BDT.

**Comment by yipengsun** [comment]
Also, note that the warning you may see is explained in #4.

**Comment by manuelfs** [comment]
I could run the test both in `nix` and natively (after adding the absolute paths to the README), with no warnings
```
(.virtualenv) |16:11:03|~/code/TrackerOnlyEmu$ make test-all
scripts/run2-rdx-hlt1.py ./samples/rdx-tracker_only.root ./gen/emu_hlt1.root
scripts/run2-rdx-l0_hadron.py ./samples/rdx-tracker_only.root ./gen/emu_l0_hadron.root
scripts/run2-rdx-l0_global_tis.py ./samples/rdx-tracker_only.root ./gen/emu_l0_global_tis.root
```

I can run the plots natively, but somehow inside `nix` I get some errors
```
(.virtualenv) |16:09:12|~/code/lhcb-ntuples-gen/studies/trigger_emulation-l0_hadron_tos_debug$ ./l0_hadron_tos_debug.sh 
Traceback (most recent call last):
  File "../../lib/python/TrackerOnlyEmu/scripts/run2-rdx-l0_hadron.py", line 199, in <module>
    d0_et_emu_frame = bdt_frame.Define(
cppyy.gbl.std.runtime_error: Template method resolution failed:
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
Traceback (most recent call last):
  File "../../lib/python/TrackerOnlyEmu/scripts/run2-rdx-l0_hadron.py", line 199, in <module>
    d0_et_emu_frame = bdt_frame.Define(
cppyy.gbl.std.runtime_error: Template method resolution failed:
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
```

**Comment by manuelfs** [comment]
The application of the emulation works both in `nix` and native (after adding the customary `../../scripts/` to `haddcut.py`)
```
|16:25:24|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_trigger_emulation_sample$ ./skimmed_sample_from_DstMuNu.sh 
Output file: rdx-tracker_only.root
Adding ../../run2-rdx/samples/Dst_D0--21_04_12--mc--Bd2DstMuNu--2016--md--py8-sim09j-dv45-subset.root...
Start skimming...
Processing tree: TupleB0/DecayTree
```

The making of the training sample gives some `Error in <TTree::SetBranchStatus>: unknown branch` errors in both, but then it gives additional errors in `nix`
```
(.virtualenv) |16:23:01|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ ./bdt_train_sample_from_DstMuNu.sh 
Output file: /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/bdt_sample_raw.root
Adding /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/../../ntuples/0.9.4-trigger_emulation/Dst_D0-mc/Dst_D0--21_04_21--mc--MC_2016_Beam6500GeV-2016-MagDown-Nu1.6-25ns-Pythia8_Sim09j_Trig0x6139160F_Reco16_Turbo03a_Filtered_11574021_D0TAUNU.SAFESTRIPTRIG.DST.root...
Start skimming...
Processing tree: TupleB0/DecayTree
Error in <TTree::SetBranchStatus>: unknown branch -> d0_et_emu_no_bdt
Error in <TTree::SetBranchStatus>: unknown branch -> rdiff_k_pi
Traceback (most recent call last):
  File "/Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/../../lib/python/TrackerOnlyEmu/scripts/run2-rdx-l0_hadron.py", line 199, in <module>
    d0_et_emu_frame = bdt_frame.Define(
cppyy.gbl.std.runtime_error: Template method resolution failed:
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
Adding /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/bdt_sample_raw.root...
Merging all friend trees...
Output file: /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/rdx-bdt_train_sample.root
Adding /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/bdt_sample_tmp.root...
Start skimming...
Processing tree: TupleB0/DecayTree
Error in <TTree::SetBranchStatus>: unknown branch -> d0_et_emu_no_bdt
Error in <TTree::SetBranchStatus>: unknown branch -> rdiff_k_pi

(.virtualenv) |16:31:42|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ ll
total 42M
-rw-r--r-- 1 manuelf  14M Jul 30 16:31 bdt_sample_raw.root
-rw-r--r-- 1 manuelf  14M Jul 30 16:31 bdt_sample_tmp.root
-rwxr-xr-x 1 manuelf 1002 Jul 30 16:24 bdt_train_sample_from_DstMuNu.sh
-rw-r--r-- 1 manuelf  800 Jul 29 10:12 l0hadron_bdt_train_sample.yml
-rw-r--r-- 1 manuelf  14M Jul 30 16:31 rdx-bdt_train_sample.root
```

but is fine natively
```
|16:24:01|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ ./bdt_train_sample_from_DstMuNu.sh 
Output file: /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/bdt_sample_raw.root
Adding /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/../../ntuples/0.9.4-trigger_emulation/Dst_D0-mc/Dst_D0--21_04_21--mc--MC_2016_Beam6500GeV-2016-MagDown-Nu1.6-25ns-Pythia8_Sim09j_Trig0x6139160F_Reco16_Turbo03a_Filtered_11574021_D0TAUNU.SAFESTRIPTRIG.DST.root...
Start skimming...
Processing tree: TupleB0/DecayTree
Error in <TTree::SetBranchStatus>: unknown branch -> d0_et_emu_no_bdt
Error in <TTree::SetBranchStatus>: unknown branch -> rdiff_k_pi
Adding /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/bdt_sample_raw.root...
Adding /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/emu_l0_hadron.root...
Merging all friend trees...
Output file: /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/rdx-bdt_train_sample.root
Adding /Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/bdt_sample_tmp.root...
Start skimming...
Processing tree: TupleB0/DecayTree

|16:30:41|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ ll
total 235000
-rw-r--r--  1 manuelf  staff    14M Jul 30 16:24 bdt_sample_raw.root
-rw-r--r--  1 manuelf  staff    33M Jul 30 16:25 bdt_sample_tmp.root
-rwxr-xr-x  1 manuelf  staff   1.0K Jul 30 16:24 bdt_train_sample_from_DstMuNu.sh
-rw-r--r--  1 manuelf  staff    47M Jul 30 16:24 emu_l0_hadron.root
-rw-r--r--  1 manuelf  staff   800B Jul 29 10:12 l0hadron_bdt_train_sample.yml
-rw-r--r--  1 manuelf  staff    19M Jul 30 16:25 rdx-bdt_train_sample.root
```

**Comment by manuelfs** [comment]
After copying `lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/rdx-bdt_train_sample.root` into `TrackerOnlyEmu/samples`, I can also run the training of the BDT both in `nix` and natively
```
(.virtualenv) |16:50:46|~/code/TrackerOnlyEmu$ make train-l0-hadron-bdt
scripts/run2-rdx-l0_hadron_train_bdt.py ./samples/rdx-bdt_train_sample.root ./gen/bdt.pickle \
	--max-depth 4 \
	--debug-ntuple ./gen/debug_bdt.root \
	--test-ntuple ./gen/test_bdt.root
Start training for a regression BDT...
BDT fitted. It takes a total of 9.00 sec
Export trained BDT...
Generate debug ntuple...
Generate test ntuple...
```

I wonder whether the installation of python 3.9.6 somehow polluted `nix`, but for now, it seems I can run everything natively.

**Comment by yipengsun** [comment]
This error message is expected:
```
Error in <TTree::SetBranchStatus>: unknown branch -> d0_et_emu_no_bdt
Error in <TTree::SetBranchStatus>: unknown branch -> rdiff_k_pi
```

The unexpected ones are these:
```

Traceback (most recent call last):
  File "/Users/manuelf/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample/../../lib/python/TrackerOnlyEmu/scripts/run2-rdx-l0_hadron.py", line 199, in <module>
    d0_et_emu_frame = bdt_frame.Define(
cppyy.gbl.std.runtime_error: Template method resolution failed:
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
  ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void>::Define(basic_string_view<char,char_traits<char> > name, basic_string_view<char,char_traits<char> > expression) =>
    runtime_error: Column "d0_et_emu_no_bdt" is not in a dataset and is not a custom column been defined.
```

I don't think your native ROOT installation would pollute nix. Can you try `which python` and `which python3` inside the nix shell to make sure they are still using the Python from local `.virtualenv`?

Also, if you set `PYTHONPATH`, it's probably a good idea to temporarily unset it and see if that helps.

**Comment by yipengsun** [comment]
You can also check `PYTHONPATH` inside a nix shell and see if it only contains nix store entries. For example, on my computer:
```
$ echo $PYTHONPATH
> ./.virtualenv/lib/python3.8/site-packages/:/nix/store/l4s8rbj8xyjg8nbhbfdprsmznba1465l-root-6.24.02/lib:/nix/store/dkqs0lxn1r6y82bxzfdq1fsc99a67b9l-python3.8-jedi-2020-08-06/lib/python3.8/site-packages:/nix/store/a6ld63kg347s3k1p3f0nk56mwp78b5hc-python3.8-parso-0.8.1/lib/python3.8/site-packages:/nix/store/2nhfiak8a30vw67mxksc2kdb69np2jcw-python3-3.8.9/lib/python3.8/site-packages:/nix/store/z29yxjazszkrjnpsmz24kxz2vwi7awjj-python3.8-flake8-3.9.2/lib/python3.8/site-packages:/nix/store/4dcid514sprc9h17nsvdqz2q43rrxwx2-python3.8-pyflakes-2.3.1/lib/python3.8/site-packages:/nix/store/llawhgrhxh9zr605sz8ly8jgnnc8i1xn-python3.8-pycodestyle-2.7.0/lib/python3.8/site-packages:/nix/store/far5p5p7kz61xdq4v85j9py33w7cn9ks-python3.8-mccabe-0.6.1/lib/python3.8/site-packages:/nix/store/9l6y1n8zhwc3faqak34m3rmz8nd57497-python3.8-pylint-2.7.2/lib/python3.8/site-packages:/nix/store/9j7j5jiaavakq4lrmvhd97813xjs9aw5-python3.8-astroid-2.5.1/lib/python3.8/site-packages:/nix/store/j6s68wlra55mvp40rvwk9y8yd10zbi6w-python3.8-lazy-object-proxy-1.6.0/lib/python3.8/site-packages:/nix/store/1akhzxf6rpdl5bivnmhhia7ddzqf7r0n-python3.8-wrapt-1.12.1/lib/python3.8/site-packages:/nix/store/cks4f95pcdabg5llf3lyigzyjvaqbqkg-python3.8-isort-5.6.4/lib/python3.8/site-packages:/nix/store/cpbc7kc964mr9zjr5sqzv6v3jrr76szb-python3.8-toml-0.10.2/lib/python3.8/site-packages:/nix/store/mwvvjjkrnssns22qf7yhj3lxlps8ml0p-python3.8-virtualenvwrapper-4.8.4/lib/python3.8/site-packages:/nix/store/3zl5sknv30m0v4nfzllyj98xk6y8q5cj-python3.8-stevedore-3.3.0/lib/python3.8/site-packages:/nix/store/m5w9dh7zrh354jkk18mmg1wjfan9hznf-python3.8-pbr-5.6.0/lib/python3.8/site-packages:/nix/store/fdws6y02z2iifyixpd9dhwval0i245dv-python3.8-setuptools-54.2.0/lib/python3.8/site-packages:/nix/store/zn4haxpv5j9ilccvw7vxxwbfb84vhl5i-python3.8-six-1.16.0/lib/python3.8/site-packages:/nix/store/1nfjcm1fs52hwhqinbkylggsdymbvwyz-python3.8-virtualenv-20.4.7/lib/python3.8/site-packages:/nix/store/2ki7lglmcgm58ksqp1rd41cmnicmhwb4-python3.8-appdirs-1.4.4/lib/python3.8/site-packages:/nix/store/hnv54x4i766n581g6rjxqk7q2jagwac3-python3.8-distlib-0.3.2/lib/python3.8/site-packages:/nix/store/hawnrnxqvimy2nf4mcbb8zy00i70lx59-python3.8-filelock-3.0.12/lib/python3.8/site-packages:/nix/store/8cp29bwpk21k8x0vlbb6an88jbhg9v0r-python3.8-virtualenv-clone-0.5.4/lib/python3.8/site-packages
```

**Comment by yipengsun** [comment]
Another thing to check is the she-bang of the actual script, in this case `run2-rdx-l0_hadron.py`. A good shebang should be something like this:
```python
#!/usr/bin/env python3
# ^^^^ good
```

If you hard-code Python 3, instead of using `/usr/bin/env`, it would be bad:
```python
#!/usr/local/bin/python3
# ^^^^ bad
```

**Comment by yipengsun** [comment]
Also check `bash` inside your nix shell:
```
which bash
```

and see if it's in the nix store.

**Comment by manuelfs** [comment]
Everything seems to point to `/nix/store/`, I don't set `PYTHONPATH` and the shebangs are the nice ones that you wrote
```
(.virtualenv) |21:02:17|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ which python
/Users/manuelf/code/lhcb-ntuples-gen/.virtualenv/bin/python

(.virtualenv) |21:02:37|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ ll /Users/manuelf/code/lhcb-ntuples-gen/.virtualenv/bin/python
lrwxr-xr-x 1 manuelf 71 Jun 28 19:46 /Users/manuelf/code/lhcb-ntuples-gen/.virtualenv/bin/python -> /nix/store/p6k14ihyfaq3z4sycxr09cvgpis2zjd5-python3-3.8.9/bin/python3.8

(.virtualenv) |21:02:42|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ which python3
/Users/manuelf/code/lhcb-ntuples-gen/.virtualenv/bin/python3

(.virtualenv) |21:02:46|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ ll /Users/manuelf/code/lhcb-ntuples-gen/.virtualenv/bin/python3
lrwxr-xr-x 1 manuelf 6 Jun 28 19:46 /Users/manuelf/code/lhcb-ntuples-gen/.virtualenv/bin/python3 -> python

(.virtualenv) |21:02:51|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ echo $PYTHONPATH
./.virtualenv/lib/python3.8/site-packages/:/nix/store/lvhww4wyxly6ricmvlf97n81il7lspvp-root-6.24.02/lib:/nix/store/idj6whdn9xpa0a8kbnv6n3mqzwwbrgms-python3.8-jedi-2020-08-06/lib/python3.8/site-packages:/nix/store/fbbbicv9pwi3nln1jh7spkwmdvw50wk3-python3.8-parso-0.8.1/lib/python3.8/site-packages:/nix/store/lcm6qi612273hm48pbfma3026fdizcc0-python3-3.8.9/lib/python3.8/site-packages:/nix/store/b9llkvmcjglnln2lvhl1np1lfiqp0lja-python3.8-flake8-3.9.2/lib/python3.8/site-packages:/nix/store/y01rl5xs7xkzsjp6lkbdaxvym70gkmq6-python3.8-pyflakes-2.3.1/lib/python3.8/site-packages:/nix/store/hshncvj63dqc9crzakax9qnc38n34gqr-python3.8-pycodestyle-2.7.0/lib/python3.8/site-packages:/nix/store/b54crvigcgckqfn1mvhb9c9n2ddlqgxz-python3.8-mccabe-0.6.1/lib/python3.8/site-packages:/nix/store/xm3vk47pi6xqszsaa2p3vbfjgx4k98ak-python3.8-pylint-2.7.2/lib/python3.8/site-packages:/nix/store/kxjln99b615505a6b7c13ihxy9brz1r6-python3.8-astroid-2.5.1/lib/python3.8/site-packages:/nix/store/6xsh5hviv1p4dwaz7ars6ca2cchsj5r5-python3.8-lazy-object-proxy-1.6.0/lib/python3.8/site-packages:/nix/store/i1kfk6k9b97b95jps1lcfdrxiqkcmbfv-python3.8-wrapt-1.12.1/lib/python3.8/site-packages:/nix/store/l1s20hvy9g5g7ck2kfq567r33qk097zq-python3.8-isort-5.6.4/lib/python3.8/site-packages:/nix/store/jilzrd4z5q8i529jx8nml1h1msb4bc7i-python3.8-toml-0.10.2/lib/python3.8/site-packages:/nix/store/8f2k7flsr01i33cippfla303ir3fj6s5-python3.8-virtualenvwrapper-4.8.4/lib/python3.8/site-packages:/nix/store/wynf1ay1dds8npgffs5q0nwil15rczj4-python3.8-stevedore-3.3.0/lib/python3.8/site-packages:/nix/store/7q0192cglg7rvjskpis412139f6x69vy-python3.8-pbr-5.6.0/lib/python3.8/site-packages:/nix/store/ylsbzadm9p8hiw98cadpjamdxj0pnc56-python3.8-setuptools-54.2.0/lib/python3.8/site-packages:/nix/store/8b7l1aydi8r19cq3lip88av8kkmlyqim-python3.8-six-1.16.0/lib/python3.8/site-packages:/nix/store/cylf9cw28f8xppfvfji50dpp5fb5rnma-python3.8-virtualenv-20.4.7/lib/python3.8/site-packages:/nix/store/3ylhlr249ilwpps4ylh1fb5v7mxkr69a-python3.8-appdirs-1.4.4/lib/python3.8/site-packages:/nix/store/mnb5zqh0n5qismdl3slh97p74nsj395n-python3.8-distlib-0.3.2/lib/python3.8/site-packages:/nix/store/i1bamnpivhk1yjdykc69kp7w8j9p3jac-python3.8-filelock-3.0.12/lib/python3.8/site-packages:/nix/store/ysspr213lcxyzpc7kgs5adnm1fs263fm-python3.8-virtualenv-clone-0.5.4/lib/python3.8/site-packages

(.virtualenv) |21:02:58|~/code/lhcb-ntuples-gen/studies/ntuple-RDX_l0_hadron_tos_training_sample$ which bash
/nix/store/jdp2n7mjwzmz8h6lrjbcj2xf5vih0s76-bash-4.4-p23/bin/bash
```

Mysterious.

**Comment by yipengsun** [comment]
We should fix this. The weird thing is: The script failed in `lhcb-ntuples-gen` actually worked in its own project, `TrackerOnlyEmu` (because `make test-all` also calls the same script), so there must be some small but important inconsistencies.

**Comment by yipengsun** [comment]
Can you try to remove the `.virtualenv` in the `lhcb-ntuples-gen` root folder, enter a new nix shell, then `make install-dep` again? Maybe something in the virtualenv is wrong.

**Comment by yipengsun** [comment]
You can also check the `.virtualenv/pyvenv.cfg` and see if it looks like this (the hash values are expected to be different):
```cfg
home = /nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9
implementation = CPython
version_info = 3.8.9.final.0
virtualenv = 20.4.3
include-system-site-packages = false
base-prefix = /nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9
base-exec-prefix = /nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9
base-executable = /nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/bin/python3.8
```

**Comment by yipengsun** [comment]
Also, can you just run this single line in that folder:
```bash
$L0EMU ${INPUT_NTP} $DIR/emu_l0_hadron.root -t TupleB0/DecayTree
```

**Comment by manuelfs** [comment]
Interesting, after removing `lhcb-ntuples-gen/.virtualenv` and doing `make install-dep` again, all the scripts above work inside `nix` 🎉

I must have messed up the set up indeed.

**Comment by yipengsun** [comment]
Not necessarily any fault on your part. It may just be we switched from ROOT 6.24.00 -> 6.24.02 and the old virtualenv was relying on some files from ROOT 6.24.00.

FYI, the potential problem due to inconsistencies of `.virtuelenv` is already documented at [here](https://umd-lhcb.github.io/lhcb-ntuples-gen/ntupling/installation/#install-nix). The general idea is you just delete it if there's something wrong.

**Comment by manuelfs** [comment]
@yipengsun The `L0_Hadron` trigger is basically `triggerET>3744 && nSPD<450`, right? Why is the SPD cut not applied for the BDT training? And why do you apply it on the debug ntuple generated by `run2-rdx-l0_hadron.py`?

I'm guessing that it is because we won't have `nSPD` in Tracker-only MC and the variables in the BDT are not particularly sensitive to `nSPD` anyway.

**Comment by manuelfs** [comment]
Another question. Why does the ntuple used for the BDT training [1] have fewer branches than the ntuple used to emulate the trigger and apply the BDT [2]?

It is probably not a big deal, since the missing branches are things like `k_MC12TuneV2_ProbNNmu` or `k_OWNPV_X` that we don't seem to use, and the branches that we do use seem similar on a first glance, but I'm just checking they're congruent.

[1]:  `lhcb-ntuples-gen/ntuples/0.9.4-trigger_emulation/Dst_D0-mc/Dst_D0--21_04_21--mc--MC_2016_Beam6500GeV-2016-MagDown-Nu1.6-25ns-Pythia8_Sim09j_Trig0x6139160F_Reco16_Turbo03a_Filtered_11574021_D0TAUNU.SAFESTRIPTRIG.DST.root`
[2]:  `lhcb-ntuples-gen/run2-rdx/samples/Dst_D0--21_04_12--mc--Bd2DstMuNu--2016--md--py8-sim09j-dv45-subset.root`

**Comment by yipengsun** [comment]
> @yipengsun The `L0_Hadron` trigger is basically `triggerET>3744 && nSPD<450`, right? Why is the SPD cut not applied for the BDT training? And why do you apply it on the debug ntuple generated by `run2-rdx-l0_hadron.py`?

I think so. The `nSPD < 450` is supposedly required but we don't cut on it in `L0_Hadron` emulation directly, supposedly due to the fact that Tracker-only doesn't have this variable.

I applied this cuts in the debug ntuple just because we are supposed to apply it in the end, and it makes plotting easier, because we have all cuts applied already by default so we don't have to apply this cut for each individual plot.

> I'm guessing that it is because we won't have `nSPD` in Tracker-only MC and the variables in the BDT are not particularly sensitive to `nSPD` anyway.
I never thought about it, and I think your reasoning makes sense.

**Comment by yipengsun** [comment]
> Another question. Why does the ntuple used for the BDT training [1](%60lhcb-ntuples-gen/ntuples/0.9.4-trigger_emulation/Dst_D0-mc/Dst_D0--21_04_21--mc--MC_2016_Beam6500GeV-2016-MagDown-Nu1.6-25ns-Pythia8_Sim09j_Trig0x6139160F_Reco16_Turbo03a_Filtered_11574021_D0TAUNU.SAFESTRIPTRIG.DST.root%60) have fewer branches than the ntuple used to emulate the trigger and apply the BDT [2](%60lhcb-ntuples-gen/run2-rdx/samples/Dst_D0--21_04_12--mc--Bd2DstMuNu--2016--md--py8-sim09j-dv45-subset.root%60)?

I already dropped some branch at lxplus level. The original ntuples have identical tree structures. I just wanted to reduce the ntuple size.

> It is probably not a big deal, since the missing branches are things like `k_MC12TuneV2_ProbNNmu` or `k_OWNPV_X` that we don't seem to use, and the branches that we do use seem similar on a first glance, but I'm just checking they're congruent.

**Comment by yipengsun** [comment]
I wrote a ntuple splitter, available [here](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/master/scripts/split_train_vali_test.py).

I did a local test:
```
$ split_train_vali_test.py test.root TupleB0/DecayTree -d
loaded test.root with 23841 entries
sample: train, cuts: 0 <= rand_split && rand_split < 35
wrote ./test_train.root with 8286 entries
sample: valid, cuts: 35 <= rand_split && rand_split < 70
wrote ./test_valid.root with 8294 entries
sample: test, cuts: 70 <= rand_split && rand_split <= 100
wrote ./test_test.root with 7236 entries
```

The general usage is:
```
split_train_vali_test.py <input_ntp> <input_tree> --debug -o <output_folder>
```

The counter provided by `RDataFrame` is not accurate, as they differ from the actual ntuple numbers. I kept the splitting branch, `rand_split`, in each ntuple, and checked manually that the selections are working correctly.

The `test.root` is actually `run2-rdx/samples/Dst_D0--21_07_30--mc--Bd2DstMuNu--2016--md--py8-sim09j-dv45-subset.root`

**Comment by yipengsun** [comment]
This is Manuel's trigger emulation report: https://github.com/umd-lhcb/group-talks/blob/master/phys_group_meetings/21-08-25_manuelf_rdx_status_ml.pdf

**Comment by yipengsun** [comment]
Now the XGB and BDT training/application has been integrated into a single script: `run2-rdx-l0_hadron_tos.py` and XGB as the default regressor.
